services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: control_car_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "02040638"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - CarControlNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend-node:
    build:
      context: ./backend/app
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:02040638@db:5432/control_car_db?schema=public"
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - CarControlNetwork
  backend-django:
    build:
      context: ./backend/system
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_NAME: control_car_db
      DB_USER: postgres
      DB_PASSWORD: "02040638"
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: "django-insecure-chave-secreta-padrao-para-docker-dev"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://18.118.187.20:3000,http://18.118.187.20:3001,"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - CarControlNetwork
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://18.118.187.20:3001"
    networks:
      - CarControlNetwork

volumes:
  postgres_data:
    driver: local

networks:
  CarControlNetwork:
    external: true